/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class domain_service_algOutput_AlgGpuRunStep */

#ifndef _Included_domain_service_algOutput_AlgGpuRunStep
#define _Included_domain_service_algOutput_AlgGpuRunStep
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     domain_service_algOutput_AlgGpuRunStep
 * Method:    calcOnCuda
 * Signature: (Ldomain/core/algOutput/GepAlgRun;)V
 */
JNIEXPORT void JNICALL Java_domain_service_algOutput_AlgGpuRunStep_calcOnCuda
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
